// Generated by ego on Wed Jun 17 09:26:54 2015.
// DO NOT EDIT

package command
import (
"fmt"
"html"
"io"
"strings"
)
//line command/templates/plugin_template.go.ego:1
 func PluginTmpl(w io.Writer, pkgName string) error  {
//line command/templates/plugin_template.go.ego:1
_, _ = fmt.Fprint(w, "package ")
//line command/templates/plugin_template.go.ego:1
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  pkgName )))
//line command/templates/plugin_template.go.ego:2
_, _ = fmt.Fprint(w, "\n\n")
//line command/templates/plugin_template.go.ego:4
_, _ = fmt.Fprint(w, "\n\nimport (\n\t\"github.com/kyokomi/slackbot/plugins\"\n\t\"golang.org/x/net/context\"\n)\n\ntype pluginKey string\n\nfunc init() {\n\tplugins.AddPlugin(pluginKey(\"")
//line command/templates/plugin_template.go.ego:13
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  pkgName )))
//line command/templates/plugin_template.go.ego:13
_, _ = fmt.Fprint(w, "Message\"), ")
//line command/templates/plugin_template.go.ego:13
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  strings.Title(pkgName) )))
//line command/templates/plugin_template.go.ego:13
_, _ = fmt.Fprint(w, "Message{})\n}\n\ntype ")
//line command/templates/plugin_template.go.ego:16
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  strings.Title(pkgName) )))
//line command/templates/plugin_template.go.ego:16
_, _ = fmt.Fprint(w, "Message struct {\n}\n\nfunc (r ")
//line command/templates/plugin_template.go.ego:19
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  strings.Title(pkgName) )))
//line command/templates/plugin_template.go.ego:19
_, _ = fmt.Fprint(w, "Message) CheckMessage(ctx context.Context, message string) (bool, string) {\n\t// TODO: execute message check\n\treturn true, message\n}\n\nfunc (r ")
//line command/templates/plugin_template.go.ego:24
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  strings.Title(pkgName) )))
//line command/templates/plugin_template.go.ego:24
_, _ = fmt.Fprint(w, "Message) DoAction(ctx context.Context, message string) bool {\n\t// TODO: message action\n\t//plugins.SendMessage(ctx, message)\n\treturn true // next ok\n}\n\nvar _ plugins.BotMessagePlugin = (*")
//line command/templates/plugin_template.go.ego:30
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  strings.Title(pkgName) )))
//line command/templates/plugin_template.go.ego:30
_, _ = fmt.Fprint(w, "Message)(nil)\n")
return nil
}
