// Automatically generated by MockGen. DO NOT EDIT!
// Source: koha_api.go

package kohaimage

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of KohaAPI interface
type MockKohaAPI struct {
	ctrl     *gomock.Controller
	recorder *_MockKohaAPIRecorder
}

// Recorder for MockKohaAPI (not exported)
type _MockKohaAPIRecorder struct {
	mock *MockKohaAPI
}

func NewMockKohaAPI(ctrl *gomock.Controller) *MockKohaAPI {
	mock := &MockKohaAPI{ctrl: ctrl}
	mock.recorder = &_MockKohaAPIRecorder{mock}
	return mock
}

func (_m *MockKohaAPI) EXPECT() *_MockKohaAPIRecorder {
	return _m.recorder
}

func (_m *MockKohaAPI) GetImageURL() string {
	ret := _m.ctrl.Call(_m, "GetImageURL")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockKohaAPIRecorder) GetImageURL() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetImageURL")
}
